export BROWSER=firefox
export TERM=ghostty
export QT_QPA_PLATFORMTHEME="qt6ct"
export GTK_THEME=adw-gtk3-dark
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus 
export SDL_IM_MODULE=ibus
export RESTIC_COMPRESSION=max
export RESTIC_PASSWORD_FILE="$HOME/Restic/.pass"
export STEAM_LINUX_RUNTIME_LOG_LEVEL=0
