[Appearance]\ncustom_palette=true\ncolor_scheme_path=/home/leifrstein/.local/share/color-schemes/DankMatugen.colors\n
icon_theme=Papirus
color_scheme_path=/home/leifrstein/.local/share/color-schemes/DankMatugen.colors
custom_palette=true
