theme = "catppuccin_mocha"

[editor]
bufferline = "multiple"
cursorline = true
cursorcolumn = true
color-modes = true

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "separator", "file-modification-indicator"]
right = ["diagnostics", "separator", "file-type", "separator", "selections", "separator", "position", "file-encoding"]
separator = ""

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 120000
